GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "New Product",
  "price": 0,
  "description": "No description."
}

###
GET http://localhost:3000/product/0

###
PATCH http://localhost:3000/product/181
Content-Type: application/json

{
  "price": 56
}

###
DELETE  http://localhost:3000/product/181
